#!/bin/bash

set -e

# not to sleep for 1 hour
caffeinate -u -t 3600  

# homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# R & misc
brew install unzip vim emacs tmux wget screen r
brew cask install rstudio

# python
wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-MacOSX-x86_64.sh
bash Anaconda3-5.2.0-MacOSX-x86_64.sh -b
echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile

# test
success=true
if !((type "jupyter" > /dev/null 2>&1) && (type "python" > /dev/null 2>&1)); then
    echo "ERROR: python & jupyter not installed"
    success=false
fi
if !((type "r" > /dev/null 2>&1) && ([ -e /Applications/RStudio.app ])); then
    echo "ERROR: R & RStudio not installed"
    success=false
fi
if [ ! $success ]; then
    exit 1
else
    echo "SUCCESS"
fi
