#!/bin/bash
set -e
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install unzip vim emacs tmux wget screen r pyenv
brew cask install rstudio

pyenv install 3.6.8
pyenv global 3.6.8
pip install numpy pandas matplotlib seaborn scikit-learn tqdm fastprogress jupyter
