#!/bin/bash
set -e

# homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# R & misc
brew install unzip vim emacs tmux wget screen r
brew cask install rstudio

# python
wget https://repo.anaconda.com/archive/Anaconda3-5.2.0-MacOSX-x86_64.sh
bash Anaconda3-5.2.0-MacOSX-x86_64.sh -b
echo 'export PATH="$HOME/anaconda3/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile

# test
success=true

jupyter_exist=$(type "jupyter" > /dev/null 2>&1)
python_exist=$(type "python" > /dev/null 2>&1)
if [ !($python_exist && $jupyter_exist) ]; then
    echo "ERROR: python/jupyter not installed"
    success=false
fi

r_exist=$(type "r" > /dev/null 2>&1)
if [ ! $r_exist ]; then
    echo "ERROR: R not installed"
    success=false
fi

if [ $success ]; then
    echo "SUCCESS"
else
    exit 1
fi
